//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsCoreApplication.DataLayer.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHART_THONGKETHEOTUAN
    {
        public int Id { get; set; }
        public Nullable<int> NgayDuLieu { get; set; }
        public Nullable<int> TuanDuLieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
