//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsCoreApplication.DataLayer.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFDBEntities : DbContext
    {
        public EFDBEntities()
            : base("name=EFDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CHITIETDKKHAM> TB_CHITIETDKKHAM { get; set; }
        public virtual DbSet<TB_HINHTHUCKCB> TB_HINHTHUCKCB { get; set; }
        public virtual DbSet<TB_KHACHHANG> TB_KHACHHANG { get; set; }
        public virtual DbSet<TB_PHONGKHAM> TB_PHONGKHAM { get; set; }
        public virtual DbSet<TB_TRANGTHAI> TB_TRANGTHAI { get; set; }
    }
}
