//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsCoreApplication.DataLayer.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long id { get; set; }
        public string NewsTitle { get; set; }
        public string ShortDescription { get; set; }
        public string NewsContent { get; set; }
        public string Thumb { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<long> UserCreated { get; set; }
        public Nullable<long> UserUpdate { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<long> idNewsCategory { get; set; }
    }
}
