//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsCoreApplication.DataLayer.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHITIETDKKHAM
    {
        public int MADK { get; set; }
        public int MAKH { get; set; }
        public Nullable<int> MAPK { get; set; }
        public System.DateTime NGAYDANGKY { get; set; }
        public Nullable<int> MATRANGTHAI { get; set; }
        public Nullable<int> MAHTKCB { get; set; }
    }
}
