//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsCoreApplication.DataLayer.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_KHACHHANG
    {
        public int MAKH { get; set; }
        public string TENKH { get; set; }
        public string NAMSINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public Nullable<bool> DKBHYT { get; set; }
    }
}
